workflows:
  android-light-workflow:
    name: Android Light APK Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Download Offline ONNX Models
        script: |
          mkdir -p assets/models/en_ar
          echo "Downloading encoder_model.onnx..."
          curl -L -f --retry 3 -o assets/models/en_ar/encoder_model.onnx https://huggingface.co/onnx-community/opus-mt-en-ar/resolve/main/onnx/encoder_model_int8.onnx
          echo "Downloading decoder_model.onnx..."
          curl -L -f --retry 3 -o assets/models/en_ar/decoder_model.onnx https://huggingface.co/onnx-community/opus-mt-en-ar/resolve/main/onnx/decoder_model_int8.onnx
          ls -lh assets/models/en_ar
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Light Flutter APK
        script: |
          flutter build apk --release --split-per-abi --obfuscate --split-debug-info=build/app/outputs/symbols
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
